import { useCallback, useState } from 'react';
import { useResource } from '../hooks/useResource';
import { addDays, adherence, dateRange, formatDay, habitSummary, PILLARS, streak, taskDue } from '../lib/domain';
import { Badge, Button, Empty, ErrorNotice, Icon, Loading, Meter, PageHeading, SectionHeading, Stat } from '../components/ui';
import PillarEditor from '../components/PillarEditor';
import TaskList from '../components/TaskList';
import TrendChart from '../components/TrendChart';

export default function Patient({ api, profile, today, page, navigate, notify }) {
  const [period, setPeriod] = useState(14); const [recordDate, setRecordDate] = useState(today); const [editor, setEditor] = useState(null);
  const days = page === 'achievements' ? 365 : page === 'progress' ? period : 30;
  const loader = useCallback(() => api.patientData(profile.id, addDays(today, -(days - 1)), today), [api, profile.id, today, days]);
  const resource = useResource(loader);
  if (resource.loading && !resource.data) return <Loading />;
  if (resource.error) return <ErrorNotice message={resource.error} retry={resource.reload} />;
  if (!resource.data) return null;
  const { records, tasks, completions } = resource.data;
  const todayRecords = records.filter(r => r.date === today);
  const todayTasks = tasks.filter(t => taskDue(t, today)); const todayAdherence = adherence(tasks, completions, [today]);
  const recent = habitSummary(records.filter(r => r.date >= addDays(today, -6)));
  const summary = habitSummary(records); const currentStreak = streak(records, today);
  const dates = dateRange(today, page === 'progress' ? period : 7);
  const chartDays = dates.map(date => summary.daily.find(d => d.date === date) || { date, score: null, coverage: 0 });
  const open = key => setEditor(key);
  const editDate = page === 'pillars' ? recordDate : today;
  const selectedRecords = records.filter(r => r.date === recordDate);
  const pillarCards = (list, editable = true) => <div className="pillar-grid">{PILLARS.map(p => { const result = habitSummary(list).pillars.find(s => s.key === p.key); const saved = list.some(r => r.pillar === p.key); return <button className={`pillar-card tone-border-${p.color}`} key={p.key} disabled={!editable} onClick={() => open(p.key)}><div className="pillar-card-top"><span className={`icon-tile tone-${p.color}`}><Icon name={p.icon} size={24} /></span>{saved ? <span className="saved-dot"><Icon name="check" size={14} /></span> : <Icon name="plus" size={16} />}</div><h3>{p.name}</h3><p>{saved ? 'Registrado · editar' : '¿Cómo estuvo tu día?'}</p><div className="pillar-value"><strong>{result.score ?? '—'}</strong><span>{result.score == null ? 'Por registrar' : '/ 100'}</span></div><Meter value={result.score} color={p.color} label={p.name} /></button>; })}</div>;
  return <><div className="page-enter">
    {page === 'home' && <>
      <PageHeading eyebrow="CADA DÍA ES UN NUEVO COMIENZO" title={`Hola, ${profile.full_name.split(' ')[0]}.`}>Hagamos espacio para lo que te hace bien.</PageHeading>
      <section className="welcome-card"><div className="welcome-copy"><Badge>Tu bienestar, paso a paso</Badge><h2>No tiene que ser perfecto.<br />Solo tiene que ser tuyo.</h2><p>Escúchate, registra cómo te sientes y celebra los pequeños avances de hoy.</p><Button onClick={() => navigate('pillars')} icon="arrow">Registrar mi día</Button></div><div className="wellness-art" aria-hidden="true"><div className="art-orbit" /><div className="art-orbit inner" /><div className="art-center"><Icon name="leaf" size={65} /></div><span className="art-bubble art-sun"><Icon name="sun" size={25} /></span><span className="art-bubble art-heart"><Icon name="heart" size={24} /></span><span className="art-bubble art-moon"><Icon name="moon" size={24} /></span><span className="art-caption">CRECER A TU RITMO</span></div></section>
      <div className="stats-grid"><Stat label="Tu plan de hoy" value={`${todayAdherence.completed}/${todayAdherence.total}`} caption={todayAdherence.total ? 'actividades completadas' : 'sin actividades programadas'} icon="check" /><Stat label="Pilares registrados" value={`${todayRecords.length}/6`} caption="un momento para observarte" icon="leaf" tone="blue" /><Stat label="Constancia reciente" value={`${currentStreak} ${currentStreak === 1 ? 'día' : 'días'}`} caption="racha dentro de los últimos 30 días" icon="sun" tone="orange" /></div>
      <div className="content-columns"><section className="panel"><SectionHeading title="Tu plan de hoy" action={<Badge tone="neutral">{formatDay(today)}</Badge>}>Lo que tu equipo preparó para ti.</SectionHeading><TaskList tasks={todayTasks} completions={completions} day={today} api={api} onChanged={resource.reload} /></section><aside className="panel weekly-panel"><SectionHeading title="Una mirada a tu semana" /><div className="weekly-score"><strong>{recent.score ?? '—'}</strong><span>indicador de hábitos / 100</span></div><TrendChart days={chartDays} compact /><p className="microcopy">{recent.days} de 7 días con registros. Los espacios vacíos son días sin información.</p><Button variant="secondary" className="full-width" onClick={() => navigate('progress')} icon="chart">Ver mi progreso</Button></aside></div>
      <SectionHeading title="Tus seis pilares" action={<button className="text-link" onClick={() => navigate('pillars')}>Ver todos <Icon name="arrow" size={16} /></button>}>Cada uno es una forma de cuidarte.</SectionHeading>{pillarCards(todayRecords)}
    </>}
    {page === 'pillars' && <><PageHeading eyebrow="UN MOMENTO PARA TI" title="¿Cómo estuvo tu día?" action={<div className="date-field"><label htmlFor="record-date">Fecha del registro</label><input id="record-date" type="date" value={recordDate} min={addDays(today, -29)} max={today} onChange={e => { if (e.target.value) setRecordDate(e.target.value); }} /></div>}>Registra lo que viviste, sin buscar un día perfecto.</PageHeading><div className="registration-summary"><div><strong>{selectedRecords.length} de 6 pilares</strong><span>registrados el {formatDay(recordDate)}</span></div><Meter value={selectedRecords.length / 6 * 100} label="Pilares registrados" /><span className="score-chip">{habitSummary(selectedRecords).score ?? '—'} <small>/ 100</small></span></div>{pillarCards(selectedRecords)}<div className="info-card"><Icon name="info" /><div><strong>Tu registro, tu contexto.</strong><p>Los valores se guardan tal como los ingresas. El indicador resume los pilares disponibles; un dato faltante no cuenta como cero. Puedes editar los últimos 30 días.</p></div></div><ScoreExplanation /></>}
    {page === 'progress' && <><PageHeading eyebrow="MIRA LO QUE HAS CONSTRUIDO" title="Tu progreso, a tu ritmo." action={<div className="segmented" aria-label="Período">{[7, 14, 30, 90].map(n => <button key={n} aria-pressed={period === n} className={period === n ? 'selected' : ''} onClick={() => setPeriod(n)}>{n} días</button>)}</div>}>Del {formatDay(dates[0])} al {formatDay(today)}. Cada registro ayuda a ver tu recorrido.</PageHeading><div className="stats-grid"><Stat label="Indicador de hábitos" value={summary.score} caption="promedio de los días registrados" icon="leaf" /><Stat label="Cobertura del período" value={`${summary.days}/${period}`} caption="días con información" icon="calendar" tone="blue" /><Stat label="Cumplimiento del plan" value={adherence(tasks, completions, dates).score == null ? '—' : `${adherence(tasks, completions, dates).score}%`} caption="actividades programadas completadas" icon="check" tone="purple" /></div><section className="panel"><SectionHeading title="Tu recorrido" action={<Badge>Hábitos</Badge>}>Puntajes de los pilares disponibles, agrupados por día.</SectionHeading>{summary.days ? <TrendChart days={chartDays} /> : <Empty title="Tu recorrido empieza con un registro" action={<Button onClick={() => navigate('pillars')}>Registrar mis pilares</Button>}>Aquí aparecerá tu evolución.</Empty>}</section><div className="content-columns equal"><section className="panel"><SectionHeading title="Pilar por pilar" />{summary.pillars.map(p => <div className="pillar-row" key={p.key}><span className={`icon-tile tone-${p.color}`}><Icon name={p.icon} /></span><div><div className="row-between"><strong>{p.name}</strong><span>{p.score ?? 'Sin datos'}</span></div><Meter value={p.score} color={p.color} label={p.name} /></div></div>)}</section><section className="panel"><SectionHeading title="Tus datos personales" /><div className="body-stats"><div><strong>{profile.weight ?? '—'}<small> kg</small></strong><span>Peso actual</span></div><div><strong>{profile.height ?? '—'}<small> cm</small></strong><span>Estatura</span></div><div><strong>{profile.weight && profile.height ? (profile.weight / (profile.height / 100) ** 2).toFixed(1) : '—'}</strong><span>IMC calculado</span></div><div><strong>{profile.body_fat ?? '—'}<small> %</small></strong><span>Grasa corporal</span></div></div><p className="microcopy">Datos declarados en tu perfil. El IMC no se interpreta ni clasifica automáticamente.</p><Button variant="secondary" onClick={() => navigate('profile')}>Actualizar mis datos</Button></section></div><ScoreExplanation /></>}
    {page === 'achievements' && <><PageHeading eyebrow="LOS PEQUEÑOS AVANCES IMPORTAN" title="Celebra tu constancia.">Tus registros de los últimos 365 días. Cada día cuenta, incluso cuando toca volver a empezar.</PageHeading><div className="stats-grid"><Stat label="Racha actual" value={currentStreak} caption="días consecutivos, incluyendo ayer si hoy aún no registras" icon="sun" tone="orange" /><Stat label="Días registrados" value={summary.days} caption="en los últimos 365 días" icon="calendar" /><Stat label="Pilares completados" value={records.length} caption="registros personales en el período" icon="leaf" tone="blue" /></div><div className="achievement-grid">{[{ name: 'El primer paso', text: 'Tu primer día con un registro.', achieved: summary.days >= 1, icon: 'leaf' }, { name: 'Encontrando tu ritmo', text: 'Una racha actual de 3 días.', achieved: currentStreak >= 3, icon: 'activity' }, { name: 'Una semana contigo', text: 'Una racha actual de 7 días.', achieved: currentStreak >= 7, icon: 'sun' }, { name: 'Una mirada completa', text: 'Registra los seis pilares en un mismo día.', achieved: summary.daily.some(d => d.coverage === 6), icon: 'award' }, { name: 'Un hábito que crece', text: '30 días registrados en el último año.', achieved: summary.days >= 30, icon: 'heart' }, { name: 'Volver también cuenta', text: '10 días registrados, aunque no sean seguidos.', achieved: summary.days >= 10, icon: 'calendar' }].map(a => <article className={`achievement ${a.achieved ? 'unlocked' : ''}`} key={a.name}><span className="achievement-symbol"><Icon name={a.icon} size={34} /></span><Badge tone={a.achieved ? 'green' : 'neutral'}>{a.achieved ? 'Alcanzado' : 'A tu ritmo'}</Badge><h2>{a.name}</h2><p>{a.text}</p></article>)}</div></>}
    {resource.loading && <p className="refreshing" role="status">Actualizando…</p>}
  </div>{editor && <PillarEditor key={`${editDate}-${editor}`} pillarKey={editor} record={records.find(r => r.date === editDate && r.pillar === editor)} date={editDate} api={api} userId={profile.id} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); notify('Tu registro quedó guardado.'); void resource.reload(); }} />}</>;
}
function ScoreExplanation() {
  return <details className="score-explanation"><summary>Cómo se calcula el indicador de hábitos</summary><p>Versión 2 · Orientativo, no clínico. Se calculan puntajes entre 0 y 100 por pilar; el día promedia únicamente los pilares registrados y el período promedia sus días con datos.</p><ul><li>Nutrición: porciones respecto a una referencia de 5 y calidad declarada.</li><li>Movimiento: pasos respecto a 8.000 y minutos respecto a 30, con igual peso.</li><li>Sueño y conexión: la calidad o conexión declarada de 1 a 10.</li><li>Calma: nivel de estrés de 1 a 10, invertido.</li><li>Consumo: cigarrillos y alcohol con escalas invertidas limitadas a 0–100.</li></ul><p>Estas referencias son parámetros del producto, no metas personalizadas ni recomendaciones médicas. Los registros antiguos se recalculan para mostrar una misma fórmula, sin sobrescribir sus datos. Las mediciones inválidas se excluyen.</p></details>;
}
